"""Create parsed_messages table with foreign key to device

Revision ID: 2622e5a9fef8
Revises: 6a465cc4e610
Create Date: 2024-10-06 22:26:36.850201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2622e5a9fef8'
down_revision = '6a465cc4e610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_hardware_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('u', sa.String(length=50), nullable=True),
    sa.Column('p', sa.String(length=50), nullable=True),
    sa.Column('cv', sa.Integer(), nullable=True),
    sa.Column('hw', sa.Integer(), nullable=True),
    sa.Column('fw', sa.String(length=50), nullable=True),
    sa.Column('sv', sa.Integer(), nullable=True),
    sa.Column('src', sa.Integer(), nullable=True),
    sa.Column('pv', sa.Integer(), nullable=True),
    sa.Column('hv', sa.Integer(), nullable=True),
    sa.Column('th', sa.Integer(), nullable=True),
    sa.Column('tc', sa.Integer(), nullable=True),
    sa.Column('ot0', sa.String(length=50), nullable=True),
    sa.Column('ot1', sa.String(length=50), nullable=True),
    sa.Column('ot3', sa.String(length=50), nullable=True),
    sa.Column('ot17', sa.String(length=50), nullable=True),
    sa.Column('ot18', sa.String(length=50), nullable=True),
    sa.Column('ot19', sa.String(length=50), nullable=True),
    sa.Column('ot25', sa.String(length=50), nullable=True),
    sa.Column('ot26', sa.String(length=50), nullable=True),
    sa.Column('ot27', sa.String(length=50), nullable=True),
    sa.Column('ot28', sa.String(length=50), nullable=True),
    sa.Column('ot34', sa.String(length=50), nullable=True),
    sa.Column('ot56', sa.String(length=50), nullable=True),
    sa.Column('ot125', sa.String(length=50), nullable=True),
    sa.Column('parsed_ot0', sa.JSON(), nullable=True),
    sa.Column('parsed_ot1', sa.Float(), nullable=True),
    sa.Column('parsed_ot3', sa.JSON(), nullable=True),
    sa.Column('parsed_ot17', sa.Float(), nullable=True),
    sa.Column('parsed_ot18', sa.Float(), nullable=True),
    sa.Column('parsed_ot19', sa.Float(), nullable=True),
    sa.Column('parsed_ot25', sa.Float(), nullable=True),
    sa.Column('parsed_ot26', sa.Float(), nullable=True),
    sa.Column('parsed_ot27', sa.Float(), nullable=True),
    sa.Column('parsed_ot28', sa.Float(), nullable=True),
    sa.Column('parsed_ot34', sa.Float(), nullable=True),
    sa.Column('parsed_ot56', sa.Float(), nullable=True),
    sa.Column('parsed_ot125', sa.Float(), nullable=True),
    sa.Column('otime', sa.Integer(), nullable=True),
    sa.Column('kp', sa.Float(), nullable=True),
    sa.Column('ti', sa.Float(), nullable=True),
    sa.Column('td', sa.Float(), nullable=True),
    sa.Column('frc', sa.Float(), nullable=True),
    sa.Column('out', sa.Float(), nullable=True),
    sa.Column('orx', sa.Integer(), nullable=True),
    sa.Column('ot', sa.Integer(), nullable=True),
    sa.Column('pd', sa.Float(), nullable=True),
    sa.Column('dd', sa.Float(), nullable=True),
    sa.Column('oo', sa.Integer(), nullable=True),
    sa.Column('ta', sa.Integer(), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('sl', sa.Integer(), nullable=True),
    sa.Column('dv', sa.Integer(), nullable=True),
    sa.Column('csv', sa.Integer(), nullable=True),
    sa.Column('lrn', sa.Float(), nullable=True),
    sa.Column('to', sa.Integer(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('sd', sa.Integer(), nullable=True),
    sa.Column('hlp', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_hardware_id'], ['device.hardware_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_messages')
    # ### end Alembic commands ###
