"""Change message column to JSON

Revision ID: 6a465cc4e610
Revises: de6b8dfd4d15
Create Date: 2024-09-12 19:35:57.985724

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6a465cc4e610'
down_revision = 'de6b8dfd4d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_messages', schema=None) as batch_op:
        batch_op.alter_column('message',
                              existing_type=sa.VARCHAR(),
                              type_=sa.JSON(),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_messages', schema=None) as batch_op:
        batch_op.alter_column('message',
                              existing_type=sa.JSON(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)

    # ### end Alembic commands ###
