"""Create device_messages table with foreign key to device

Revision ID: de6b8dfd4d15
Revises: dd1fab5001db
Create Date: 2024-09-12 19:21:10.830255

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de6b8dfd4d15"
down_revision = "dd1fab5001db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_hardware_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_hardware_id"],
            ["device.hardware_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_messages")
    # ### end Alembic commands ###
